### ISSUE TITLE
API Pulls

### ISSUE THREAD

**Issue by brynne-eastman** [ZichKoding/TuneItUp#4]
-Is keyword search possible?
-Where are we fetching from? SongKick, Music Brainz;

**Comment by ZichKoding** [comment]
We are dropping musicbrainz for now and moving onto iTunes and YouTube Data API. 

I've managed to get a videoID and use it in a link which works but now I have to get channel ID Data endpoint because it'll use the video ID and give some random channel or first channel alphabetically or chronologically with that same video ID which is a no go.
